### ISSUE TITLE
template not found, "evidence.html"

### ISSUE THREAD

**Issue by yoheeb** [trac-hacks/evidencetracplugin#3]
Hi, looks like a cool plugin start.  i am a fan of "Evidence based scheduling", well parts of it, i use velocity at a project level.   anyway:

I tried to install your plugin.  It installs.  I do get the estimate below the ticket details, however if i click on it:
TemplateNotFound: Template "evidence.html" not found

It would help if you added some install/config information on trac hacks.  Do we need to create/edit custom fields?  How do we get to these reports there seems to be in the package (no nav addition is made, no upgrades required, etc.)  Also, tracing on git-hub and not trac-hacks will net you less feedback, if you have to create an account just to provide feedback, many won't bother unless they happen to use git-hub already.

Again, I like the direction, hope it ends up working in the end.

I realize you are in early dev here, here' the trace, although template not found is pretty self explanitory.:

<pre>
Most recent call last:

    * File "C:/usr/bin/Python26/lib/site-packages/trac/web/main.py", line 513, in _dispatch_request
      Code fragment:
      Line  
      508   try:
      509   if not env and env_error:
      510   raise HTTPInternalError(env_error)
      511   try:
      512   dispatcher = RequestDispatcher(env)
      513   dispatcher.dispatch(req)
      514   except RequestDone:
      515   pass
      516   resp = req._response or []
      517    
      518   except HTTPException, e:
      Local variables:
      Name  Value
      dispatcher    <trac.web.main.RequestDispatcher object at 0x0147B7D0>
      e     TemplateNotFound('Template "evidence.html" not found',)
      env   <trac.env.Environment object at 0x0123B110>
      env_error     None
      req   <Request "GET '/ticket/33/ebs'">
      resp  []
    * File "C:/usr/bin/Python26/lib/site-packages/trac/web/main.py", line 256, in dispatch
      Code fragment:
      Line  
      251   pprint(data, out)
      252   req.send(out.getvalue(), 'text/plain')
      253   else:
      254   output = chrome.render_template(req, template,
      255   data,
      256   content_type)
      257   # Give the session a chance to persist changes
      258   req.session.save()
      259   req.send(output, content_type or 'text/html')
      260   else:
      261   self._post_process_request(req)
      Local variables:
      Name  Value
      chosen_handler    <evidence.ticket_ebs.EvidenceSchedulingTicket object at 0x0147B730>
      chrome    <trac.web.chrome.Chrome object at 0x0147B450>
      content_type  None
      data  {'dateinfo': <function dateinfo at 0x01658870>, 'owner': u'Jay', ...
      err   (<class 'genshi.template.loader.TemplateNotFound'>, ...
      handler   <evidence.ticket_ebs.EvidenceSchedulingTicket object at 0x0147B730>
      req   <Request "GET '/ticket/33/ebs'">
      resp  ('evidence.html', {'dateinfo': <function dateinfo at 0x01658870>, 'owner': ...
      self  <trac.web.main.RequestDispatcher object at 0x0147B7D0>
      template  'evidence.html'
    * File "C:/usr/bin/Python26/lib/site-packages/trac/web/chrome.py", line 808, in render_template
      Code fragment:
      Line  
      803   message = req.session.pop('chrome.%s.%d' % (type_, i))
      804   req.chrome[type_].append(Markup(message))
      805   except KeyError:
      806   pass
      807    
      808   template = self.load_template(filename, method=method)
      809   data = self.populate_data(req, data)
      810   data['chrome']['content_type'] = content_type
      811    
      812   stream = template.generate(**data)
      813    
      Local variables:
      Name  Value
      content_type  'text/html'
      data  {'dateinfo': <function dateinfo at 0x01658870>, 'owner': u'Jay', ...
      filename  'evidence.html'
      fragment  False
      i     0
      method    'xhtml'
      req   <Request "GET '/ticket/33/ebs'">
      self  <trac.web.chrome.Chrome object at 0x0147B450>
      type_     'notices'
    * File "C:/usr/bin/Python26/lib/site-packages/trac/web/chrome.py", line 779, in load_template
      Code fragment:
      Line  
      774   if method == 'text':
      775   cls = NewTextTemplate
      776   else:
      777   cls = MarkupTemplate
      778    
      779   return self.templates.load(filename, cls=cls)
      780    
      781   def render_template(self, req, filename, data, content_type=None,
      782   fragment=False):
      783   """Render the `filename` using the `data` for the context.
      784    
      Local variables:
      Name  Value
      cls   <class 'genshi.template.markup.MarkupTemplate'>
      filename  'evidence.html'
      method    'xhtml'
      self  <trac.web.chrome.Chrome object at 0x0147B450>
    * File "C:/usr/bin/Python26/lib/site-packages/genshi/template/loader.py", line 246, in load 
</pre>

<pre>
Trac    0.12
CustomFieldAdmin    0.2.2
FullBlog    0.1.1
Genshi  0.6
pysqlite    2.4.1
Python  2.6.5 (r265:79096, Mar 19 2010, 21:48:26) [MSC v.1500 32 bit (Intel)]
setuptools  0.6c11
SQLite  3.5.9
jQuery  1.4.2
</pre>

**Comment by ironsmile** [comment]
Somehow I manged to remove that template on one of the last commits.

Thanks for the advice. I don't expect to start paying much attention at the trac-hacks for the time being. Maybe when it feels ready for worry-free usage I'll think of a way to synergize all of the feedback.
