### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/evidencetracplugin#9]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to find trac-hacks plugins, such as yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. More information can be found in the [blog post](http://trac-hacks.org/blog/2015-02-21-trac-hacks-on-github).

Kind regards,
Ryan

(Apologies if I open a ticket against two of your plugins. I'm doing a manual search of GitHub to find Trac plugins and invite plugin authors; it's sometimes difficult to keep everything straight).

**Comment by ironsmile** [comment]
Hi!

I will be more than happy to join your organization and transfer my two plugins.

I am not exactly sure how do they fare with newer tracs. I'm only running them on my old installation which is at version 0.11.5. The second plugin is a [notification filter](https://github.com/ironsmile/NoNotifyTiming-trac-plugin) which I consider a dirty hack at best. At this point of time they do not represent my own standard of quality but it is unlikely I will have the time to improve them any time soon. That is why I find your idea of merging all plugins under one organization more than excellent!

Now, what do I do next?

**Comment by rjollos** [comment]
Thanks! You should receive an invite to join the trac-hacks organization. You'll have general Admin access to the trac-hacks organization which will allow you to execute [these steps](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts) and transfer the repository. After you transfer the repository I'll remove you from the Admin team, create an Admin group for your repository and make you the Admin for your repository.

**Comment by ironsmile** [comment]
Here you go! My two repos are now in the trac-hacks organization.

**Comment by rjollos** [comment]
Looks good. Thanks!
